import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();

  const onClickRemoteButton = () => {
    router.push("/remote");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          안녕하셔유~ microfrontend host 앱입니당~
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>여기는 pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <button onClick={onClickRemoteButton} className={styles.card}>
            <code className={styles.code}>여기는 remote react app</code>
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
